const testData = [
    {
        "Id": "1",
        "Owner": null,
        "Name": "Complaint",
        "Title": "33. Скарги пацієнта:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "1"
    },
    {
        "Id": "6",
        "Owner": null,
        "Name": "DiseaseAnamnesis",
        "Title": "34. Анамнез хвороби:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "1"
    },
    {
        "Id": "9",
        "Owner": null,
        "Name": "LifeAnamnesis",
        "Title": "35. Анамнез життя:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "1"
    },
    {
        "Id": "12",
        "Owner": null,
        "Name": "Tuberculosis",
        "Title": "Туберкульоз:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "parent-radio",
        "Page": "1"
    },
    {
        "Id": "15",
        "Owner": "18",
        "Name": "TuberculosisYear",
        "Title": null,
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "date",
        "Page": "1"
    },
    {
        "Id": "18",
        "Owner": "12",
        "Name": "Tuberculosis",
        "Title": null,
        "Value": "хворів",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "radio",
        "Page": "1"
    },
    {
        "Id": "21",
        "Owner": "12",
        "Name": "Tuberculosis",
        "Title": null,
        "Value": "не хворів",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "radio",
        "Page": "1"
    },
    {
        "Id": "34",
        "Owner": null,
        "Name": "Complaint",
        "Title": "33. Скарги пацієнта:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "2"
    },
    {
        "Id": "36",
        "Owner": null,
        "Name": "DiseaseAnamnesis",
        "Title": "34. Анамнез хвороби:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "2"
    },
    {
        "Id": "39",
        "Owner": null,
        "Name": "LifeAnamnesis",
        "Title": "35. Анамнез життя:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "textarea",
        "Page": "2"
    },
    {
        "Id": "32",
        "Owner": null,
        "Name": "Tuberculosis2",
        "Title": "Туберкульоз2:",
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "parent-radio",
        "Page": "3"
    },
    {
        "Id": "35",
        "Owner": "38",
        "Name": "TuberculosisYear2",
        "Title": null,
        "Value": null,
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "text",
        "Page": "3"
    },
    {
        "Id": "38",
        "Owner": "32",
        "Name": "Tuberculosis2",
        "Title": null,
        "Value": "хворів",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "radio",
        "Page": "3"
    },
    {
        "Id": "31",
        "Owner": "32",
        "Name": "Tuberculosis2",
        "Title": null,
        "Value": "не хворів",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": null,
        "Width": null,
        "Padding": null,
        "Checked": false,
        "Type": "radio",
        "Page": "3"
    }
];

export default testData;