const testData = [
    {
        "Id": "1",
        "Name": "Complaint",
        "Value": "33. Скарги пацієнта:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "275",
                "Name": "DiseaseDate",
                "Value": "",
                "TextBefore": "Дата початку хвороби: ",
                "TextAfter": "",
                "InLine": "1",
                "Width": "80",
                "Padding": "0",
                "Checked": false,
                "Owner": null,
                "Type": "date"
            },
            {
                "Id": "278",
                "Name": "DiseaseTime",
                "Value": "",
                "TextBefore": "Час початку хвороби",
                "TextAfter": "",
                "InLine": "1",
                "Width": "50",
                "Padding": "0",
                "Checked": false,
                "Owner": null,
                "Type": "hour"
            }
        ],
        "Checked": "sdfg sdfgsd f",
        "Type": "textarea"
    },
    {
        "Id": "2",
        "Name": "DiseaseAnamnesis",
        "Value": "34. Анамнез хвороби:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [],
        "Checked": "вап ыва пыв",
        "Type": "textarea"
    },
    {
        "Id": "3",
        "Name": "LifeAnamnesis",
        "Value": "35. Анамнез життя:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [],
        "Checked": 0,
        "Type": "none"
    },
    {
        "Id": "4",
        "Name": "Tuberculosis",
        "Value": "Туберкульоз:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "1",
                "Name": "Tuberculosis",
                "Value": "не хворів",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "2",
                "Name": "Tuberculosis",
                "Value": "хворів",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": "хворів",
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "3",
                "Name": "TuberculosisYear",
                "Value": "",
                "TextBefore": "у ",
                "TextAfter": " році",
                "InLine": "1",
                "Width": "40",
                "Padding": null,
                "Checked": false,
                "Owner": "2",
                "Type": "text"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "5",
        "Name": "ViralHepatitis",
        "Value": "Вірусний гепатит:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "4",
                "Name": "ViralHepatitis",
                "Value": "не хворів",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "5",
                "Name": "ViralHepatitis",
                "Value": "переніс вірусний гепатит",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": "переніс вірусний гепатит",
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "37",
                "Name": "ViralHepatitisGroupA",
                "Value": "A",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": null,
                "Width": "220",
                "Padding": "180",
                "Checked": "A",
                "Owner": "5",
                "Type": "checkbox"
            },
            {
                "Id": "40",
                "Name": "ViralHepatitisYearA",
                "Value": null,
                "TextBefore": "у ",
                "TextAfter": " році",
                "InLine": "1",
                "Width": "40",
                "Padding": null,
                "Checked": false,
                "Owner": "37",
                "Type": "text"
            },
            {
                "Id": "38",
                "Name": "ViralHepatitisGroupB",
                "Value": "B",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": null,
                "Width": "220",
                "Padding": "180",
                "Checked": "B",
                "Owner": "5",
                "Type": "checkbox"
            },
            {
                "Id": "41",
                "Name": "ViralHepatitisYearB",
                "Value": null,
                "TextBefore": "у ",
                "TextAfter": " році",
                "InLine": "1",
                "Width": "40",
                "Padding": null,
                "Checked": "1998",
                "Owner": "38",
                "Type": "text"
            },
            {
                "Id": "39",
                "Name": "ViralHepatitisGroupC",
                "Value": "C",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": null,
                "Width": "220",
                "Padding": "180",
                "Checked": false,
                "Owner": "5",
                "Type": "checkbox"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "6",
        "Name": "SexuallyTransmittedDiseases",
        "Value": "Венеричні захворювання:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "6",
                "Name": "SexuallyTransmittedDiseases",
                "Value": "заперечує",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "7",
                "Name": "SexuallyTransmittedDiseases",
                "Value": "переніс",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "7",
        "Name": "AIDS",
        "Value": "ВІЛ\/СНІД:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "8",
                "Name": "AIDS",
                "Value": "не хворів",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "9",
                "Name": "AIDS",
                "Value": "вперше виявлено",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "8",
        "Name": "Injuries",
        "Value": "Травми:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "10",
                "Name": "Injuries",
                "Value": "заперечує",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "11",
                "Name": "Injuries",
                "Value": "переніс",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "9",
        "Name": "SurgicalIntervention",
        "Value": "Перенесені оперативні втручання:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "12",
                "Name": "SurgicalIntervention",
                "Value": "не було",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            },
            {
                "Id": "13",
                "Name": "SurgicalIntervention",
                "Value": "переніс",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "radio"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    },
    {
        "Id": "10",
        "Name": "BadHabits",
        "Value": "Шкідливі звички:",
        "Owner": "0",
        "OwnerName": "---",
        "TextBefore": null,
        "TextAfter": null,
        "InLine": "0",
        "Width": null,
        "Padding": null,
        "Options": [
            {
                "Id": "14",
                "Name": "Smoking",
                "Value": "паління",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": "паління",
                "Owner": null,
                "Type": "checkbox"
            },
            {
                "Id": "15",
                "Name": "Alcohol",
                "Value": "алкогольна залежність",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "checkbox"
            },
            {
                "Id": "16",
                "Name": "Drugs",
                "Value": "прийом наркотичних або токсичних речовин",
                "TextBefore": null,
                "TextAfter": null,
                "InLine": "1",
                "Width": null,
                "Padding": null,
                "Checked": false,
                "Owner": null,
                "Type": "checkbox"
            }
        ],
        "Checked": 0,
        "Type": "radio"
    }
];

export default testData;