export const typesUI = {

    INITIALIZE:           'INITIALIZE',
    LOAD_DATA:            'LOAD_DATA',
    CHECKBOX_UPDATE:      'CHECKBOX_UPDATE',
    TEXTAREA_UPDATE:      'TEXTAREA_UPDATE',
    INPUT_UPDATE:         'INPUT_UPDATE',
    RADIO_BUTTON_UPDATE:  'RADIO_BUTTON_UPDATE',
    PAGINATION_UPDATE:    'PAGINATION_UPDATE',
    FORM_UPDATE:          'FORM_UPDATE',
  
  };