export const typesUI = {

    LOAD_DATA:            'LOAD_DATA',
    DATE_UPDATE:          'DATE_UPDATE',
    CHECKBOX_UPDATE:      'CHECKBOX_UPDATE',
    TEXTAREA_UPDATE:      'TEXTAREA_UPDATE',
    INPUT_UPDATE:         'INPUT_UPDATE',
    RADIO_BUTTON_UPDATE:  'RADIO_BUTTON_UPDATE',
    PAGINATION_UPDATE:    'PAGINATION_UPDATE',
    FORM_UPDATE:          'FORM_UPDATE',
    FORM_SUBMIT:          'FORM_SUBMIT',
    CONFIRM_POPUP_SHOW:   'CONFIRM_POPUP_SHOW',
    CONFIRM_POPUP_HIDE:   'CONFIRM_POPUP_HIDE',
  
  };